---
Title of the Project: "Reproducible Research - Peer Assessment 1"
Author: "Deepak Mishra"
Date: "Sunday, October 18, 2015"
---


## Loading and preprocessing the data
```{r}
##1. Loading relveant libraries and the dataset

> activity = read.csv("C:/Users/577037/Desktop/Activity Monitoring Data/activity.csv")

```

## What is mean total number of steps taken per day?

> total_of_steps_per_day <- sum(activity$steps, na.rm = TRUE)
> total_of_steps_per_day
Output = [1] 570608

Histogram of number of steps taken per day

> total_steps_each_day <- aggregate(steps~date, data=activity, FUN=sum, na.rm=TRUE)
> hist(total_steps_each_day$steps)

## What is the average daily activity pattern?

Calculate mean and median of steps take per day

> total_steps_each_day_mean <- mean(total_steps_each_day$steps)
> total_steps_each_day_median <- median(total_steps_each_day$steps)

Plot of each 5 minute interval on steps taken per day

> five_minutes_average <- aggregate(steps~interval, data=activity, FUN=mean, na.rm=TRUE)
> plot(x = five_minutes_average$interval, y = five_minutes_average$steps, type = "l") 

## Maximum number of steps on 5-minute interval

> max_steps <- max(five_minutes_average$steps)
> for (i in 1:288) 
> {
>    if (five_minutes_average$steps[i] == max_steps)
>        five_minute_interval_at_max_steps <- five_minutes_average$interval[i]
> }
> five_minute_interval_at_max_steps 
Output = [1] 835

## Inputing missing values

Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

> total_na <- 0
> for (i in 1:17568)
> {
>    if(is.na(activity$steps[i])) 
>        total_na <- total_na+1 
> }
> total_na
Output = [1] 2304

##2. Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. 

Create a new dataset that is equal to the original dataset but with the missing data filled in.


> activity_filled_in <- activity
> for (i in 1:17568) # loop to find the na
> {
>    if(is.na(activity_filled_in$steps[i])) # if steps is na store the pointer 
>    { 
>        five_minute_pointer <- activity_filled_in$interval[i] #store the value of pointer to find the mean on five minute > >interval
>        for (j in 1:288)  # loop to find the value of pointer on the data frame of five minute interval
>        {
>            if (five_minutes_average$interval[j] == five_minute_pointer) # finding the value of mean of five minute interval > data frame
>                activity_filled_in$steps[i] <- five_minutes_average$steps[j] # replacing the na by the mean in that fime  >minute interval 

 >       }
 >   }
> }

Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. 

> total_steps_each_day_filled_in <- aggregate(steps~date, data=activity_filled_in, FUN=sum, na.rm=TRUE)
> hist(total_steps_each_day_filled_in$steps)

Calculate the mean and median and explain the imoact of imputing missing data on the estimates of the total daily number of steps

> total_steps_each_day_mean_filled_in <- mean(total_steps_each_day_filled_in$steps)
> total_steps_each_day_median_filled_in <- median(total_steps_each_day_filled_in$steps)


## Are there differences in activity patterns between weekdays and weekends?

creating a char vector (week_day) 
> week <- wday(activity_filled_in$date)
> week_day <- week
> for (i in 1:17568) # loop to find the na
>{
>    if(week[i] == 1)
>        week_day[i] <- 'weekend'
>    if(week[i] == 2)
>        week_day[i] <- 'weekday'
>    if(week[i] == 3)
>        week_day[i] <- 'weekday'
>    if(week[i] == 4)
>        week_day[i] <- 'weekday'
>    if(week[i] == 5)
>        week_day[i] <- 'weekday'
>    if(week[i] == 6)
>        week_day[i] <- 'weekday'
>    if(week[i] == 7)
>        week_day[i] <- 'weekend'
> }

Creating a new factor variable in the dataset "activity_filled_in" 
> activity_filled_in$weekday <-week_day

Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).

finding the elements by "weekday" or "weekend"
> weekday <- grep("weekday",activity_filled_in$weekday)
> weekday_frame <- activity_filled_in[weekday,]
> weekend_frame <- activity_filled_in[-weekday,]


> plot(x = five_minutes_average_weekday$interval, y = five_minutes_average_weekday$steps, type = "l") 


